services:
  db:
    image: postgres:14
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data:rw

  bot:
    image: ghcr.io/bloodcloak/yatb-com
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - internal
    env_file:
      - .env

networks:
  internal: